
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 18 01:52:41 GFT 2015
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VAR = 3;
  public static final int error = 1;
  public static final int STR = 4;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int INT = 5;
}

